version: '3'
services:
  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    command: npm start
  app:
    build: ./backend
    ports:
      - "8080:80"
  db:
    image: postgres:14.1-alpine
    # Adding this to update the conf file of postgres so it can be used to get the last updated timestamp of table
    command: postgres -c track_commit_timestamp=true
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=carddragdrop
      - POSTGRES_DB=database
    ports:
      - '5432:5432'
    volumes:
      - ./database/catData.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local