version: '3'
services:
  app:
    build: .
    ports:
      - "8080:80"
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=carddragdrop
      - POSTGRES_DB=database
    ports:
      - '5432:5432'
    volumes:
      - ./database/catData.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local